blank_issues_enabled: true
contact_links:
  - name: Discussions and community
    url: https://github.com/kimdre/doco-cd/discussions
    about: Ask and answer questions, share ideas, discuss features, and more.
  - name: Documentation
    url: https://github.com/kimdre/doco-cd/wiki
    about: Find documentation, guides, and other resources in the wiki.